---
# tasks file for cloudwatch
- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: pkgs
- name: add ppas
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: ppas
